### ISSUE TITLE
Error when player connects

### ISSUE THREAD

**Issue by kdurrance** [thebigsmileXD/Spooky#7] opened 2017-11-09 09:57 UTC
I get this string of errors when a player connects to the server. The entity is never spawned.

`2017-11-09 [20:38:51] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'Slenderman v1.7.2': Call to undefined function xenialdan\Slenderman\entities\imagecreatefrompng() on xenialdan\Slenderman\EventListener
2017-11-09 [20:38:51] [Server thread/CRITICAL]: Error: "Call to undefined function xenialdan\Slenderman\entities\imagecreatefrompng()" (EXCEPTION) in "Slenderman.phar/src/xenialdan/Slenderman/entities/Slenderman" at line 26
2017-11-09 [20:38:51] [Server thread/DEBUG]: #0 Slenderman.phar/src/xenialdan/Slenderman/EventListener(89): xenialdan\Slenderman\entities\Slenderman->__construct(pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
2017-11-09 [20:38:51] [Server thread/DEBUG]: #1 src/pocketmine/plugin/MethodEventExecutor(38): xenialdan\Slenderman\EventListener->onJoin(pocketmine\event\player\PlayerJoinEvent object)
2017-11-09 [20:38:51] [Server thread/DEBUG]: #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(xenialdan\Slenderman\EventListener object, pocketmine\event\player\PlayerJoinEvent object)
2017-11-09 [20:38:51] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(721): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerJoinEvent object)
2017-11-09 [20:38:51] [Server thread/DEBUG]: #4 src/pocketmine/Player(971): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerJoinEvent object)
2017-11-09 [20:38:51] [Server thread/DEBUG]: #5 src/pocketmine/Player(919): pocketmine\Player->doFirstSpawn()
2017-11-09 [20:38:51] [Server thread/DEBUG]: #6 src/pocketmine/level/Level(2409): pocketmine\Player->sendChunk(integer 1, integer 7, pocketmine\network\mcpe\protocol\BatchPacket object)
2017-11-09 [20:38:51] [Server thread/DEBUG]: #7 src/pocketmine/level/Level(2450): pocketmine\level\Level->sendChunkFromCache(integer 1, integer 7)
2017-11-09 [20:38:51] [Server thread/DEBUG]: #8 src/pocketmine/level/format/io/ChunkRequestTask(88): pocketmine\level\Level->chunkRequestCallback(integer 1, integer 7, pocketmine\network\mcpe\protocol\BatchPacket object)
2017-11-09 [20:38:51] [Server thread/DEBUG]: #9 src/pocketmine/scheduler/AsyncPool(164): pocketmine\level\format\io\ChunkRequestTask->onCompletion(pocketmine\Server object)
2017-11-09 [20:38:51] [Server thread/DEBUG]: #10 src/pocketmine/scheduler/ServerScheduler(342): pocketmine\scheduler\AsyncPool->collectTasks()
2017-11-09 [20:38:51] [Server thread/DEBUG]: #11 src/pocketmine/Server(2522): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 2816)
2017-11-09 [20:38:51] [Server thread/DEBUG]: #12 src/pocketmine/Server(2269): pocketmine\Server->tick()
2017-11-09 [20:38:51] [Server thread/DEBUG]: #13 src/pocketmine/Server(2144): pocketmine\Server->tickProcessor()
2017-11-09 [20:38:51] [Server thread/DEBUG]: #14 src/pocketmine/Server(1734): pocketmine\Server->start()
2017-11-09 [20:38:51] [Server thread/DEBUG]: #15 src/pocketmine/PocketMine(564): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///Users/karldurrance/Documents/MinecraftPE/PocketMine-MP.phar/, string /Users/karldurrance/Documents/MinecraftPE/, string /Users/karldurrance/Documents/MinecraftPE/plugins/)
2017-11-09 [20:38:51] [Server thread/DEBUG]: #16 /Users/karldurrance/Documents/MinecraftPE/PocketMine-MP.phar(1): require(string phar:///Users/karldurrance/Documents/MinecraftPE/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
`

**Comment by kdurrance** [comment] 2017-11-09 09:59
Server is running PocketMine-MP version 1.7dev-380 "[REDACTED]" (API 3.0.0-ALPHA9)

**Comment by inxomnyaa** [comment] 2017-11-09 12:18
\imagecreatefrompng() 

gd2 is disabled in php.ini

Duplicate of second part of https://github.com/thebigsmileXD/Slenderman/issues/2

**Closed as completed by inxomnyaa** 2017-11-09 12:18 UTC
Labels: duplicate
